### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by adrianmoisey** [yola/svgify#4]
This library is actually called `vectorify`. 
Can I rename the repo to match that?
The [upload jobs](https://github.com/yola/yolatools/blob/7b85381fbeb3ecebd3d3efd2c7f039ca6923587a/projects/jenkins-job-builder/jobs/upload/npm-libs.yml) require that to happen, as they assume the library name and repo name are the same.

**Comment by stefanor** [comment]
:+1:
